### ISSUE TITLE
Error extracting 16S rRNA gene from genbank flat file

### ISSUE THREAD

**Issue by fconstancias** [linzhi2013/gbseqextractor#1]
Hello,

I am trying to extract 16S operon from a collection of genbank flat files.
 
I am very interested in your tool but got the following error:
gbseqextractor -f GCF_903181445.1_NZ_Bacteroides_fragilis_8E3_BL_hyb_genomic.gbff -types rRNA  
 
Traceback (most recent call last):
  File "/usr/local/bin/gbseqextractor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/gbseqextractor/gbseqextractor.py", line 94, in main
    fh_rrna = open(args.prefix+".rrna", 'w')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
 
Any idea wat I am doing wrong?
 
Thanks a ton.

 
python --version
Python 3.6.7

**Comment by fconstancias** [comment]
solved, I forgot the `-prefix` option.

Guanliang updated `gbseqextractor`

> I updated the script to version 0.0.2 just now, it will prompt "gbseqextractor.py: error: the following arguments are required: -prefix" if the "-prefix" is not provided, which becomes more friendly to users.
